// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import BodyController from './body_controller';
import ChartGalleryController from './chart_gallery';
import ClipboardController from './clipboard_controller';
import DataSourceQueryController from './data_source_query_controller';
import DataSourceVerificationController from './data_source_verification_controller';
import FormController from './form_controller';
import MenuController from './menu_controller';
import OtpController from './otp_controller';
import ResizeablePageController from './resizeable_page_controller';
import SearchController from './search_controller';

application.register('body', BodyController);
application.register('chart-gallery', ChartGalleryController);
application.register('clipboard', ClipboardController);
application.register('data-source-query', DataSourceQueryController);
application.register('data-source-verification', DataSourceVerificationController);
application.register('form', FormController);
application.register('menu', MenuController);
application.register('otp', OtpController);
application.register('resizeable-page', ResizeablePageController);
application.register('search', SearchController);
