// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AccountDeleteController from './account-delete-controller';
import AccordionController from './accordion-controller';
import BodyController from './body-controller';
import BreadcrumbsController from './breadcrumbs-controller';
import CardsController from './cards-controller';
import ClipboardController from './clipboard-controller';
import DataSourceVerificationController from './data-source-verification-controller';
import DataSourceWizardController from './data-source-wizard-controller';
import EchartsVisualizationController from './echarts-visualization-controller';
import FormController from './form-controller';
import MemberInviteController from './member-invite-controller';
import MenuController from './menu-controller';
import OtpController from './otp-controller';
import QueryEditorController from './query-editor-controller';
import QueryLibraryColumnsController from './query-library-columns-controller';
import QueryLibraryGroupsController from './query-library-groups-controller';
import QuerySidePanelController from './query-side-panel-controller';
import QueryResultsTableController from './query-results-table-controller';
import ResizeablePageController from './resizeable-page-controller';
import SearchController from './search-controller';
import TableController from './table-controller';
import ToastStackController from './toast-stack-controller';
import TranslationsAdminController from './translations-admin-controller';
import WorkspaceChatController from './workspace-chat-controller';

application.register('account-delete', AccountDeleteController);
application.register('accordion', AccordionController);
application.register('body', BodyController);
application.register('breadcrumbs', BreadcrumbsController);
application.register('cards', CardsController);
application.register('clipboard', ClipboardController);
application.register('data-source-verification', DataSourceVerificationController);
application.register('data-source-wizard', DataSourceWizardController);
application.register('echarts-visualization', EchartsVisualizationController);
application.register('form', FormController);
application.register('member-invite', MemberInviteController);
application.register('menu', MenuController);
application.register('otp', OtpController);
application.register('query-editor', QueryEditorController);
application.register('query-library-columns', QueryLibraryColumnsController);
application.register('query-library-groups', QueryLibraryGroupsController);
application.register('query-side-panel', QuerySidePanelController);
application.register('query-results-table', QueryResultsTableController);
application.register('resizeable-page', ResizeablePageController);
application.register('search', SearchController);
application.register('table', TableController);
application.register('toast-stack', ToastStackController);
application.register('translations-admin', TranslationsAdminController);
application.register('workspace-chat', WorkspaceChatController);
