default: &default
  total:
    label_tag: chart_type_total
    image: charts/total.svg
    label: Total
    disabled: false
    partials:
      data:
        - data_column
      appearance:
        - title
        - colors
      other:
        - post_text_label
  table:
    label_tag: chart_type_table
    image: charts/table.svg
    label: Table
    disabled: false
    partials:
      data: []
      appearance:
        - title
      other:
        - pagination
  line:
    label_tag: chart_type_line
    image: charts/line.svg
    label: Line
    disabled: false
    partials:
      data:
        - x_axis
        - y_axis
      appearance:
        - title
        - legend
        - colors
      other:
        - tooltips
  area:
    label_tag: chart_type_area
    image: charts/area.svg
    label: Area
    disabled: false
    partials:
      data:
        - x_axis
        - y_axis
      appearance:
        - title
        - legend
        - colors
      other:
        - tooltips
  stacked_area:
    label_tag: chart_type_stacked_area
    image: charts/stacked-area.svg
    label: Stacked area
    disabled: true
    partials:
      data: []
      appearance: []
      other: []
  column:
    label_tag: chart_type_column
    image: charts/column.svg
    label: Column
    disabled: false
    partials:
      data:
        - x_axis
        - y_axis
      appearance:
        - title
        - legend
        - colors
      other:
        - tooltips
  stacked_column:
    label_tag: chart_type_stacked_column
    image: charts/stacked-column.svg
    label: Stacked column
    disabled: true
    partials:
      data: []
      appearance: []
      other: []
  bar:
    label_tag: chart_type_bar
    image: charts/bar.svg
    label: Bar
    disabled: false
    partials:
      data: 
        - x_axis
        - y_axis
      appearance:
        - title
        - legend
        - colors
      other:
        - tooltips
  stacked_bar:
    label_tag: chart_type_stacked_bar
    image: charts/stacked-bar.svg
    label: Stacked bar
    disabled: true
    partials:
      data: []
      appearance: []
      other: []
  combo:
    label_tag: chart_type_combo
    image: charts/combo.svg
    label: Combo
    disabled: true
    partials:
      data: []
      appearance: []
      other: []
  pie:
    label_tag: chart_type_pie
    image: charts/pie.svg
    label: Pie
    disabled: false
    partials:
      data: []
      appearance: []
      other: []
  donut:
    label_tag: chart_type_donut
    image: charts/donut.svg
    label: Donut
    disabled: false
    partials:
      data: []
      appearance: []
      other: []

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
