common: &common
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_primary: &default_primary
  <<: *common

default_events: &default_events
  <<: *common
  migrations_paths: db/migrate_events

development:
  primary:
    <<: *default_primary
    database: sql_book_development
  events:
    <<: *default_events
    database: sql_book_events_development

test:
  primary:
    <<: *default_primary
    database: sql_book_test
  events:
    <<: *default_events
    database: sql_book_events_test

production:
  primary:
    <<: *default_primary
    url: <%= ENV["DATABASE_PRIMARY_URL"] %>
    database: sql_book_production
  events:
    <<: *default_events
    url: <%= ENV["DATABASE_EVENTS_URL"] %>
    database: sql_book_events_production
