default_primary: &default_primary
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default_primary
    database: sql_book_development

test:
  primary:
    <<: *default_primary
    database: sql_book_test

production:
  primary:
    <<: *default_primary
    database: sql_book_production
    username: sql_book
    password: <%= ENV["SQL_BOOK_DATABASE_PASSWORD"] %>
